server:
  port: 8085
spring:
  datasource:
    #druid:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.41.143:3306/award?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8             # 数据库名称
    username: root
    password: 123456
      #initial-size:  10
      #max-active:  50
      #min-idle:  10
  redis:
    host: 123.207.86.139
    password: Redis@rdtest@2018
    port: 6379
    database: 0
  jpa:
      show-sql: true # 默认false，在日志里显示执行的sql语句
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5Dialect
      hibernate:
        ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会 新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
        naming:
        #指定jpa的自动表生成策略，驼峰自动映射为下划线格式7
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl